name: Demo CI for Java Microservice

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Start build job'
        run: |
          echo "Starting the build job."
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build and test the project
      - name: Build and test
        run: mvn clean verify

      # Package the application into a JAR
      - name: Build JAR file
        run: mvn package

      # Publish the JAR file as an artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: application-jar
          path: target/*.jar
