name: Demo CI for Java Microservice

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Start build job'
        run: |
          echo "Starting the build job."
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Extract version from pom.xml
      - name: Extract version
        id: extract_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # Build and test the project
      - name: Build and test
        run: mvn clean verify

      # Publish test reports
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ env.VERSION }}
          path: target/surefire-reports/*.xml

      # Package the application into a JAR
      - name: Build JAR file
        run: mvn package

      # Publish the JAR file as an artifact with version
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-${{ env.VERSION }}.jar
          path: target/*.jar
